In [1]:
import numpy as np

In [2]:
#define the input patterns
x1=[[1,1,1,1]];
x2=[[1,-1,-1,1]];
x3=[[-1,1,-1,-1]];
x4=[[1,-1,-1,-1]];

In [3]:
#transpose of the input patterns
x11=np.transpose(x1)
x21=np.transpose(x2)
x31=np.transpose(x3)
x41=np.transpose(x4)

In [6]:
#calculate the weight matrices 
w1=x1*x11
w2=x2*x21
w3=x3*x31
w4=x4*x41

In [8]:
#calculate the sum of the weight matrices
w=w1+w2+w3+w4
print(w)


[[ 4 -2  0  2]
 [-2  4  2  0]
 [ 0  2  4  2]
 [ 2  0  2  4]]


In [10]:
#make diagonal elements zero
np.fill_diagonal(w,0)
print(w)

[[ 0 -2  0  2]
 [-2  0  2  0]
 [ 0  2  0  2]
 [ 2  0  2  0]]


In [11]:
#calculte test recall for x1
xt1=np.dot(x1,w)
print(xt1)

[[0 0 4 4]]


In [13]:
#define activation function
def activate(x,theta=0):
    return np.where(x>theta,1,np.where(x==theta,x,0))

In [14]:
#apply activation to xt1
xt1_act=activate(xt1)
print(xt1_act)

[[0 0 1 1]]


In [16]:
#test recall
if np.array_equal(x1,xt1_act):
    print("Testing complete")
else:
    print("Testing failed")

Testing failed
